POST http://localhost:8080/products
Content-Type: application/json

{
    "_id": "itemY",
    "image": "..//assets/images/felix_odenhall.jpg",
    "title": "image 2",
    "type": "environment",
    "isAvailable": true,
    "isPacked": false,
    "isShipped": false
}

### Get posts
GET http://localhost:8080/products
