POST http://localhost:8080/products
Content-Type: application/json

{
    "_id": "itemX",
    "image": "..//assets/images/castle.png",
    "title": "Moonlight Castle",
    "type": "environment",
    "isAvailable": true,
    "isPacked": false,
    "isShipped": false
}

### Get posts
GET http://localhost:8080/products
